name: manual

on:
  pull_request:
    branches:
      - master
      - feat/*
      - feature/*
      - release/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore CronScheduler.sln

    - name: Install GitVersion
      run: dotnet tool install -g GitVersion.Tool

    - name: Use GitVersion
      id: gitversion
      run: |
        semver=$(dotnet-gitversion /output json /showvariable SemVer)

    - name: Print SemVer
      run: echo "The SemVer is ${{ steps.gitversion.outputs.semver }}"

    - name: Build
      run: dotnet build CronScheduler.sln --configuration Release --no-restore /p:Version=${{ steps.gitversion.outputs.semver }}

    - name: Test
      run: dotnet test test/CronScheduler.UnitTest/CronScheduler.UnitTest.csproj --no-build --verbosity normal

    - name: Publish NuGet package
      run: |
        dotnet pack CronScheduler.sln --configuration Release --no-build /p:PackageVersion=${{ steps.gitversion.outputs.semver }}
        dotnet nuget push **/*.nupkg --source https://nuget.pkg.github.com/kdcllc/index.json --api-key ${{ secrets.NUGET_GITHUB_API_KEY }}
