name: master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore CronScheduler.sln

    - name: Install GitVersion
      run: dotnet tool install -g GitVersion.Tool

    - name: Use GitVersion
      run: dotnet gitversion /output json /showvariable SemVer
      id: gitversion

    - name: Build
      run: dotnet build CronScheduler.sln --configuration Release --no-restore /p:Version=${{ steps.gitversion.outputs.SemVer }}

    - name: Test
      run: dotnet test test/CronScheduler.UnitTest/CronScheduler.UnitTest.csproj --no-build --verbosity normal

    - name: Publish NuGet package
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: |
        dotnet pack src/YourProject/YourProject.csproj --configuration Release --output ./nupkg /p:Version=${{ steps.gitversion.outputs.SemVer }}
        dotnet nuget push ./nupkg/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
